//! Figurine domain — catalog + per-user records.

pub mod achievement;
pub mod activity;
pub mod admin;
pub mod currency;
pub mod entity;
pub mod export;
pub mod figure;
pub mod figure_photo;
pub mod figure_price;
pub mod figure_type;
pub mod follow;
pub mod gift;
pub mod location;
pub mod manga;
pub mod manga_servers;
pub mod notification;
pub mod owned;
pub mod owned_document;
pub mod photo;
pub mod preorder;
pub mod scan;
pub mod server_job;
pub mod settings;
pub mod stats;
pub mod store;
pub mod wishlist;
pub mod worker;
